// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// partition
int partition(double V[]);
RcppExport SEXP _RadixSort_partition(SEXP V[]SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type V[](V[]SEXP);
    rcpp_result_gen = Rcpp::wrap(partition(V[]));
    return rcpp_result_gen;
END_RCPP
}
// quickSort
void quickSort(double V[]);
RcppExport SEXP _RadixSort_quickSort(SEXP V[]SEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type V[](V[]SEXP);
    quickSort(V[]);
    return R_NilValue;
END_RCPP
}
// tri_digit_Rcpp
IntegerVector tri_digit_Rcpp(IntegerVector V, int rank);
RcppExport SEXP _RadixSort_tri_digit_Rcpp(SEXP VSEXP, SEXP rankSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type V(VSEXP);
    Rcpp::traits::input_parameter< int >::type rank(rankSEXP);
    rcpp_result_gen = Rcpp::wrap(tri_digit_Rcpp(V, rank));
    return rcpp_result_gen;
END_RCPP
}
// tri_digit_Rcpp_opti
IntegerVector tri_digit_Rcpp_opti(IntegerVector V, int rank);
RcppExport SEXP _RadixSort_tri_digit_Rcpp_opti(SEXP VSEXP, SEXP rankSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type V(VSEXP);
    Rcpp::traits::input_parameter< int >::type rank(rankSEXP);
    rcpp_result_gen = Rcpp::wrap(tri_digit_Rcpp_opti(V, rank));
    return rcpp_result_gen;
END_RCPP
}
// radix_sort_Rcpp
IntegerVector radix_sort_Rcpp(IntegerVector V);
RcppExport SEXP _RadixSort_radix_sort_Rcpp(SEXP VSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type V(VSEXP);
    rcpp_result_gen = Rcpp::wrap(radix_sort_Rcpp(V));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_RadixSort_partition", (DL_FUNC) &_RadixSort_partition, 1},
    {"_RadixSort_quickSort", (DL_FUNC) &_RadixSort_quickSort, 1},
    {"_RadixSort_tri_digit_Rcpp", (DL_FUNC) &_RadixSort_tri_digit_Rcpp, 2},
    {"_RadixSort_tri_digit_Rcpp_opti", (DL_FUNC) &_RadixSort_tri_digit_Rcpp_opti, 2},
    {"_RadixSort_radix_sort_Rcpp", (DL_FUNC) &_RadixSort_radix_sort_Rcpp, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_RadixSort(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
