// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// tri_digit_Rcpp
IntegerVector tri_digit_Rcpp(IntegerVector V, int rank);
RcppExport SEXP _RadixSort_tri_digit_Rcpp(SEXP VSEXP, SEXP rankSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type V(VSEXP);
    Rcpp::traits::input_parameter< int >::type rank(rankSEXP);
    rcpp_result_gen = Rcpp::wrap(tri_digit_Rcpp(V, rank));
    return rcpp_result_gen;
END_RCPP
}
// tri_digit_Rcpp_opti
IntegerVector tri_digit_Rcpp_opti(IntegerVector V, int rank);
RcppExport SEXP _RadixSort_tri_digit_Rcpp_opti(SEXP VSEXP, SEXP rankSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type V(VSEXP);
    Rcpp::traits::input_parameter< int >::type rank(rankSEXP);
    rcpp_result_gen = Rcpp::wrap(tri_digit_Rcpp_opti(V, rank));
    return rcpp_result_gen;
END_RCPP
}
// radix_sort_Rcpp
IntegerVector radix_sort_Rcpp(IntegerVector V);
RcppExport SEXP _RadixSort_radix_sort_Rcpp(SEXP VSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type V(VSEXP);
    rcpp_result_gen = Rcpp::wrap(radix_sort_Rcpp(V));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_hello_world
List rcpp_hello_world();
RcppExport SEXP _RadixSort_rcpp_hello_world() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rcpp_hello_world());
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_RadixSort_tri_digit_Rcpp", (DL_FUNC) &_RadixSort_tri_digit_Rcpp, 2},
    {"_RadixSort_tri_digit_Rcpp_opti", (DL_FUNC) &_RadixSort_tri_digit_Rcpp_opti, 2},
    {"_RadixSort_radix_sort_Rcpp", (DL_FUNC) &_RadixSort_radix_sort_Rcpp, 1},
    {"_RadixSort_rcpp_hello_world", (DL_FUNC) &_RadixSort_rcpp_hello_world, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_RadixSort(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
