# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

modulo <- function(V, m = 10L) {
    .Call(`_RadixSort_modulo`, V, m)
}

tri_digit_Rcpp_opti <- function(V, rank) {
    .Call(`_RadixSort_tri_digit_Rcpp_opti`, V, rank)
}

radix_sort_Rcpp <- function(V) {
    .Call(`_RadixSort_radix_sort_Rcpp`, V)
}

nb_decim <- function(nb) {
    .Call(`_RadixSort_nb_decim`, nb)
}

tri_digit_Rcpp_decimal <- function(V, rank) {
    .Call(`_RadixSort_tri_digit_Rcpp_decimal`, V, rank)
}

radix_sort_Rcpp_decimal <- function(V) {
    .Call(`_RadixSort_radix_sort_Rcpp_decimal`, V)
}

