# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

tri_digit_Rcpp <- function(v, rank) {
    .Call(`_RadixSort_tri_digit_Rcpp`, v, rank)
}

tri_digit_Rcpp_opti <- function(v, rank) {
    .Call(`_RadixSort_tri_digit_Rcpp_opti`, v, rank)
}

radix_sort_Rcpp <- function(v) {
    .Call(`_RadixSort_radix_sort_Rcpp`, v)
}

rcpp_hello_world <- function() {
    .Call(`_RadixSort_rcpp_hello_world`)
}

